# -*- coding: utf-8 -*-
# Generated by Django 1.9c1 on 2015-11-26 16:47
from __future__ import unicode_literals

from django.db import migrations, models
import jsonfield.fields
import open511_server.models


class Migration(migrations.Migration):

    dependencies = [
        ('open511', '0006_schedule_data'),
    ]

    operations = [
        migrations.CreateModel(
            name='ImportTaskStatus',
            fields=[
                ('created', models.DateTimeField(db_index=True, default=open511_server.models._now)),
                ('updated', models.DateTimeField(db_index=True, default=open511_server.models._now)),
                ('id', models.CharField(max_length=300, primary_key=True, serialize=False)),
                ('status_info', jsonfield.fields.JSONField(default={})),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AlterModelOptions(
            name='area',
            options={'verbose_name': 'Area', 'verbose_name_plural': 'Areas'},
        ),
        migrations.AlterModelOptions(
            name='camera',
            options={'verbose_name': 'Camera', 'verbose_name_plural': 'Cameras'},
        ),
        migrations.AlterModelOptions(
            name='jurisdiction',
            options={'verbose_name': 'Jurisdiction', 'verbose_name_plural': 'Jurisdictions'},
        ),
        migrations.AlterModelOptions(
            name='jurisdictiongeography',
            options={'verbose_name': 'Jurisdiction geography', 'verbose_name_plural': 'Jurisdiction geographies'},
        ),
        migrations.AlterModelOptions(
            name='roadevent',
            options={'verbose_name': 'Road event', 'verbose_name_plural': 'Road events'},
        ),
    ]
