# -*- coding: utf-8 -*-
# Generated by Django 1.9c1 on 2015-11-27 20:13
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('open511', '0007_add_import_status'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='importtaskstatus',
            options={'verbose_name_plural': 'Import task statuses'},
        ),
        migrations.AddField(
            model_name='camera',
            name='last_import_hash',
            field=models.CharField(blank=True, help_text='MD5 of the input XML the last time this was imported', max_length=32),
        ),
        migrations.AddField(
            model_name='roadevent',
            name='last_import_hash',
            field=models.CharField(blank=True, help_text='MD5 of the input XML the last time this was imported', max_length=32),
        ),
    ]
